// Calabria Explorer — Punti di interesse
// Modifica questo file per aggiungere o aggiornare i luoghi sulla mappa.
const POIS_DATA = [
  {
    "id": "reggio-lungomare",
    "name": "Lungomare Falcomata",
    "area": "Reggio Calabria",
    "type": "panorama",
    "categoryLabel": "Passeggiata panoramica",
    "lat": 38.11435,
    "lng": 15.65186,
    "visitMinutes": 45,
    "foodMinutes": 0,
    "imagePath": "images/pois/reggio-lungomare.jpg",
    "imageLabel": "lungomare di Reggio Calabria",
    "description": "Il tratto piu iconico del fronte mare reggino, perfetto per iniziare o chiudere la giornata."
  },
  {
    "id": "reggio-museo",
    "name": "Museo Archeologico Nazionale",
    "area": "Reggio Calabria",
    "type": "culture",
    "categoryLabel": "Museo",
    "lat": 38.11804,
    "lng": 15.65085,
    "visitMinutes": 95,
    "foodMinutes": 0,
    "imagePath": "images/pois/reggio-museo.jpg",
    "imageLabel": "museo archeologico di Reggio Calabria",
    "description": "Tappa simbolo per chi vuole costruire un itinerario culturale attorno ai Bronzi di Riace."
  },
  {
    "id": "reggio-castello",
    "name": "Castello Aragonese",
    "area": "Reggio Calabria",
    "type": "culture",
    "categoryLabel": "Monumento",
    "lat": 38.10362,
    "lng": 15.64424,
    "visitMinutes": 55,
    "foodMinutes": 0,
    "imagePath": "images/pois/reggio-castello.jpg",
    "imageLabel": "castello aragonese di Reggio Calabria",
    "description": "Fortezza urbana tra le tappe piu riconoscibili del centro storico."
  },
  {
    "id": "scilla-castello",
    "name": "Castello Ruffo",
    "area": "Scilla",
    "type": "culture",
    "categoryLabel": "Monumento",
    "lat": 38.256,
    "lng": 15.71475,
    "visitMinutes": 60,
    "foodMinutes": 0,
    "imagePath": "images/pois/scilla-castello.jpg",
    "imageLabel": "castello Ruffo di Scilla",
    "description": "Il castello domina il promontorio e regala una vista fortissima sullo Stretto."
  },
  {
    "id": "scilla-chianalea",
    "name": "Chianalea",
    "area": "Scilla",
    "type": "panorama",
    "categoryLabel": "Borgo marinaro",
    "lat": 38.2532,
    "lng": 15.7182,
    "visitMinutes": 75,
    "foodMinutes": 0,
    "imagePath": "images/pois/scilla-chianalea.jpg",
    "imageLabel": "borgo di Chianalea",
    "description": "Il tratto piu fotografato di Scilla, con case sul mare e vicoli stretti."
  },
  {
    "id": "scilla-belvedere",
    "name": "Belvedere di Piazza San Rocco",
    "area": "Scilla",
    "type": "panorama",
    "categoryLabel": "Belvedere",
    "lat": 38.25196,
    "lng": 15.71662,
    "visitMinutes": 30,
    "foodMinutes": 0,
    "imagePath": "images/pois/scilla-belvedere.jpg",
    "imageLabel": "belvedere di Scilla",
    "description": "Una sosta breve ma scenografica sopra il borgo e la costa."
  },
  {
    "id": "tropea-centro",
    "name": "Centro storico di Tropea",
    "area": "Tropea",
    "type": "culture",
    "categoryLabel": "Centro storico",
    "lat": 38.6753,
    "lng": 15.8949,
    "visitMinutes": 90,
    "foodMinutes": 0,
    "imagePath": "images/pois/tropea-centro.jpg",
    "imageLabel": "centro storico di Tropea",
    "description": "Stradine, scorci sul Tirreno e un centro storico perfetto per una mezza giornata."
  },
  {
    "id": "tropea-santamaria",
    "name": "Santa Maria dell'Isola",
    "area": "Tropea",
    "type": "panorama",
    "categoryLabel": "Belvedere",
    "lat": 38.67472,
    "lng": 15.89869,
    "visitMinutes": 50,
    "foodMinutes": 0,
    "imagePath": "images/pois/tropea-santamaria.jpg",
    "imageLabel": "Santa Maria dell'Isola a Tropea",
    "description": "Uno dei punti panoramici piu celebri della costa calabrese."
  },
  {
    "id": "tropea-marina",
    "name": "Affaccio sul mare di Tropea",
    "area": "Tropea",
    "type": "nature",
    "categoryLabel": "Costa",
    "lat": 38.67275,
    "lng": 15.89805,
    "visitMinutes": 35,
    "foodMinutes": 0,
    "imagePath": "images/pois/tropea-marina.jpg",
    "imageLabel": "mare di Tropea",
    "description": "Pausa rilassata per godersi la costa e il profilo del santuario."
  },
  {
    "id": "melito-centro",
    "name": "Centro di Melito di Porto Salvo",
    "area": "Melito di Porto Salvo",
    "type": "culture",
    "categoryLabel": "Centro urbano",
    "lat": 37.9204,
    "lng": 15.7779,
    "visitMinutes": 35,
    "foodMinutes": 0,
    "imagePath": "images/pois/melito-centro.jpg",
    "imageLabel": "Melito di Porto Salvo",
    "description": "Punto utile per costruire itinerari nella fascia ionica sud."
  },
  {
    "id": "melito-lungomare",
    "name": "Lungomare di Melito",
    "area": "Melito di Porto Salvo",
    "type": "panorama",
    "categoryLabel": "Lungomare",
    "lat": 37.91956,
    "lng": 15.77985,
    "visitMinutes": 40,
    "foodMinutes": 0,
    "imagePath": "images/pois/melito-lungomare.jpg",
    "imageLabel": "lungomare di Melito",
    "description": "Passeggiata semplice sul mare, adatta a itinerari brevi o serali."
  },
  {
    "id": "pentedattilo-borgo",
    "name": "Borgo di Pentedattilo",
    "area": "Pentedattilo",
    "type": "culture",
    "categoryLabel": "Borgo storico",
    "lat": 37.95439,
    "lng": 15.76102,
    "visitMinutes": 85,
    "foodMinutes": 0,
    "imagePath": "images/pois/pentedattilo-borgo.jpg",
    "imageLabel": "borgo di Pentedattilo",
    "description": "Tra i luoghi piu suggestivi dell'area grecanica, incastonato nella roccia."
  },
  {
    "id": "condofuri-marina",
    "name": "Condofuri Marina",
    "area": "Condofuri",
    "type": "nature",
    "categoryLabel": "Costa",
    "lat": 37.93324,
    "lng": 15.87166,
    "visitMinutes": 45,
    "foodMinutes": 0,
    "imagePath": "images/pois/condofuri-marina.jpg",
    "imageLabel": "Condofuri Marina",
    "description": "Tratto di costa tranquillo, ideale per una sosta mare e relax."
  },
  {
    "id": "ammendolea-borgo",
    "name": "Borgo di Amendolea",
    "area": "Amendolea",
    "type": "culture",
    "categoryLabel": "Borgo storico",
    "lat": 37.98873,
    "lng": 15.89287,
    "visitMinutes": 75,
    "foodMinutes": 0,
    "imagePath": "images/pois/ammendolea-borgo.jpg",
    "imageLabel": "borgo di Amendolea",
    "description": "Piccolo borgo dell'area grecanica con forte carattere paesaggistico."
  },
  {
    "id": "bova-borgo",
    "name": "Borgo di Bova",
    "area": "Bova",
    "type": "culture",
    "categoryLabel": "Borgo ellenofono",
    "lat": 37.9969,
    "lng": 15.9329,
    "visitMinutes": 85,
    "foodMinutes": 0,
    "imagePath": "images/pois/bova-borgo.jpg",
    "imageLabel": "borgo di Bova",
    "description": "Uno dei paesi piu identitari dell'area grecanica, tra storia e tradizioni."
  },
  {
    "id": "bova-belvedere",
    "name": "Belvedere di Bova",
    "area": "Bova",
    "type": "panorama",
    "categoryLabel": "Belvedere",
    "lat": 37.9961,
    "lng": 15.9342,
    "visitMinutes": 30,
    "foodMinutes": 0,
    "imagePath": "images/pois/bova-belvedere.jpg",
    "imageLabel": "belvedere di Bova",
    "description": "Affaccio sull'Aspromonte e sulla costa ionica, ottimo per una tappa fotografica."
  },
  {
    "id": "gerace-centro",
    "name": "Centro storico di Gerace",
    "area": "Gerace",
    "type": "culture",
    "categoryLabel": "Borgo medievale",
    "lat": 38.27106,
    "lng": 16.22093,
    "visitMinutes": 95,
    "foodMinutes": 0,
    "imagePath": "images/pois/gerace-centro.jpg",
    "imageLabel": "centro storico di Gerace",
    "description": "Borgo medievale dell'entroterra con un tessuto urbano tra i piu belli della zona."
  },
  {
    "id": "gerace-cattedrale",
    "name": "Cattedrale di Gerace",
    "area": "Gerace",
    "type": "culture",
    "categoryLabel": "Architettura religiosa",
    "lat": 38.27065,
    "lng": 16.22156,
    "visitMinutes": 45,
    "foodMinutes": 0,
    "imagePath": "images/pois/gerace-cattedrale.jpg",
    "imageLabel": "cattedrale di Gerace",
    "description": "Una delle visite piu forti per chi ama chiese storiche e architettura."
  },
  {
    "id": "locri-parco",
    "name": "Parco Archeologico di Locri Epizefiri",
    "area": "Locri",
    "type": "culture",
    "categoryLabel": "Archeologia",
    "lat": 38.24158,
    "lng": 16.26653,
    "visitMinutes": 95,
    "foodMinutes": 0,
    "imagePath": "images/pois/locri-parco.jpg",
    "imageLabel": "parco archeologico di Locri Epizefiri",
    "description": "Sito archeologico chiave per un itinerario storico nel versante ionico."
  },
  {
    "id": "locri-lungomare",
    "name": "Lungomare di Locri",
    "area": "Locri",
    "type": "panorama",
    "categoryLabel": "Lungomare",
    "lat": 38.2387,
    "lng": 16.2596,
    "visitMinutes": 35,
    "foodMinutes": 0,
    "imagePath": "images/pois/locri-lungomare.jpg",
    "imageLabel": "lungomare di Locri",
    "description": "Una sosta mare semplice da inserire in una giornata sul versante ionico."
  },
  {
    "id": "tropea-pranzo",
    "name": "Pranzo tipico a Tropea",
    "area": "Tropea",
    "type": "food",
    "categoryLabel": "Ristorazione",
    "lat": 38.67516,
    "lng": 15.89618,
    "visitMinutes": 75,
    "foodMinutes": 75,
    "imagePath": "images/pois/tropea-pranzo.jpg",
    "imageLabel": "piatto tipico a Tropea",
    "description": "Pausa gastronomica da inserire tra centro storico e affacci sul mare."
  },
  {
    "id": "scilla-cena",
    "name": "Cena di pesce a Scilla",
    "area": "Scilla",
    "type": "food",
    "categoryLabel": "Esperienza gastronomica",
    "lat": 38.25253,
    "lng": 15.7162,
    "visitMinutes": 80,
    "foodMinutes": 80,
    "imagePath": "images/pois/scilla-cena.jpg",
    "imageLabel": "cena di pesce a Scilla",
    "description": "Sosta food perfetta da abbinare a Chianalea e al tramonto."
  },
  {
    "id": "bova-degustazione",
    "name": "Degustazione nell'area grecanica",
    "area": "Bova",
    "type": "food",
    "categoryLabel": "Sapori locali",
    "lat": 37.99658,
    "lng": 15.93312,
    "visitMinutes": 60,
    "foodMinutes": 60,
    "imagePath": "images/pois/bova-degustazione.jpg",
    "imageLabel": "degustazione nell'area grecanica",
    "description": "Pausa gastronomica per percorsi tra borghi e tradizioni dell'entroterra."
  }
];
