// Calabria Explorer — Punti di interesse
// Modifica questo file per aggiungere o aggiornare i luoghi sulla mappa.
const POIS_DATA = [
  {
    "id": "reggio-lungomare",
    "name": "Lungomare Falcomata",
    "area": "Reggio Calabria",
    "type": "panorama",
    "categoryLabel": "Passeggiata panoramica",
    "lat": 38.11435,
    "lng": 15.65186,
    "visitMinutes": 45,
    "foodMinutes": 0,
    "imagePath": "images/pois/gallery/reggio-lungomare-1.png",
    "imageLabel": "lungomare di Reggio Calabria",
    "description": "Il tratto piu iconico del fronte mare reggino, perfetto per iniziare o chiudere la giornata.",
    "gallery": [
      "images/pois/gallery/reggio-lungomare-1.png",
      "images/pois/gallery/reggio-lungomare-2.png",
      "images/pois/gallery/reggio-lungomare-3.png",
      "images/pois/gallery/reggio-lungomare-4.png",
      "images/pois/gallery/reggio-lungomare-5.png",
      "images/pois/gallery/reggio-lungomare-6.png",
      "images/pois/gallery/reggio-lungomare-7.png"
    ]
  },
  {
    "id": "reggio-museo",
    "name": "Museo Archeologico Nazionale",
    "area": "Reggio Calabria",
    "type": "culture",
    "categoryLabel": "Museo",
    "lat": 38.11804,
    "lng": 15.65085,
    "visitMinutes": 95,
    "foodMinutes": 0,
    "imagePath": "images/pois/gallery/reggio-museo-1.png",
    "imageLabel": "museo archeologico di Reggio Calabria",
    "description": "Tappa simbolo per chi vuole costruire un itinerario culturale attorno ai Bronzi di Riace.",
    "gallery": [
      "images/pois/gallery/reggio-museo-1.png",
      "images/pois/gallery/reggio-museo-2.png",
      "images/pois/gallery/reggio-museo-3.png",
      "images/pois/gallery/reggio-museo-4.png",
      "images/pois/gallery/reggio-museo-5.png",
      "images/pois/gallery/reggio-museo-6.png"
    ]
  },
  {
    "id": "reggio-castello",
    "name": "Castello Aragonese",
    "area": "Reggio Calabria",
    "type": "culture",
    "categoryLabel": "Monumento",
    "lat": 38.10362,
    "lng": 15.64424,
    "visitMinutes": 55,
    "foodMinutes": 0,
    "imagePath": "images/pois/gallery/reggio-castello-1.png",
    "imageLabel": "castello aragonese di Reggio Calabria",
    "description": "Fortezza urbana tra le tappe piu riconoscibili del centro storico.",
    "gallery": [
      "images/pois/gallery/reggio-castello-1.png",
      "images/pois/gallery/reggio-castello-2.png",
      "images/pois/gallery/reggio-castello-3.png",
      "images/pois/gallery/reggio-castello-4.png"
    ]
  },
  {
    "id": "scilla-castello",
    "name": "Castello Ruffo",
    "area": "Scilla",
    "type": "culture",
    "categoryLabel": "Monumento",
    "lat": 38.256,
    "lng": 15.71475,
    "visitMinutes": 60,
    "foodMinutes": 0,
    "imagePath": "images/pois/gallery/scilla-castello-1.png",
    "imageLabel": "castello Ruffo di Scilla",
    "description": "Il castello domina il promontorio e regala una vista fortissima sullo Stretto.",
    "gallery": [
      "images/pois/gallery/scilla-castello-1.png",
      "images/pois/gallery/scilla-castello-2.png",
      "images/pois/gallery/scilla-castello-3.png",
      "images/pois/gallery/scilla-castello-4.png",
      "images/pois/gallery/scilla-castello-5.png"
    ]
  },
  {
    "id": "scilla-chianalea",
    "name": "Chianalea",
    "area": "Scilla",
    "type": "panorama",
    "categoryLabel": "Borgo marinaro",
    "lat": 38.2532,
    "lng": 15.7182,
    "visitMinutes": 75,
    "foodMinutes": 0,
    "imagePath": "images/pois/gallery/scilla-chianalea-1.png",
    "imageLabel": "borgo di Chianalea",
    "description": "Il tratto piu fotografato di Scilla, con case sul mare e vicoli stretti.",
    "gallery": [
      "images/pois/gallery/scilla-chianalea-1.png",
      "images/pois/gallery/scilla-chianalea-2.png",
      "images/pois/gallery/scilla-chianalea-3.png",
      "images/pois/gallery/scilla-chianalea-4.png",
      "images/pois/gallery/scilla-chianalea-5.png"
    ]
  },
  {
    "id": "scilla-belvedere",
    "name": "Belvedere di Piazza San Rocco",
    "area": "Scilla",
    "type": "panorama",
    "categoryLabel": "Belvedere",
    "lat": 38.25196,
    "lng": 15.71662,
    "visitMinutes": 30,
    "foodMinutes": 0,
    "imagePath": "images/pois/gallery/scilla-belvedere-1.png",
    "imageLabel": "belvedere di Scilla",
    "description": "Una sosta breve ma scenografica sopra il borgo e la costa.",
    "gallery": [
      "images/pois/gallery/scilla-belvedere-1.png",
      "images/pois/gallery/scilla-belvedere-2.png",
      "images/pois/gallery/scilla-belvedere-3.png",
      "images/pois/gallery/scilla-belvedere-4.png",
      "images/pois/gallery/scilla-belvedere-5.png"
    ]
  },
  {
    "id": "tropea-centro",
    "name": "Centro storico di Tropea",
    "area": "Tropea",
    "type": "culture",
    "categoryLabel": "Centro storico",
    "lat": 38.6753,
    "lng": 15.8949,
    "visitMinutes": 90,
    "foodMinutes": 0,
    "imagePath": "images/pois/gallery/tropea-centro-1.png",
    "imageLabel": "centro storico di Tropea",
    "description": "Stradine, scorci sul Tirreno e un centro storico perfetto per una mezza giornata.",
    "gallery": [
      "images/pois/gallery/tropea-centro-1.png",
      "images/pois/gallery/tropea-centro-2.png",
      "images/pois/gallery/tropea-centro-3.png",
      "images/pois/gallery/tropea-centro-4.png"
    ]
  },
  {
    "id": "tropea-santamaria",
    "name": "Santa Maria dell'Isola",
    "area": "Tropea",
    "type": "panorama",
    "categoryLabel": "Belvedere",
    "lat": 38.67472,
    "lng": 15.89869,
    "visitMinutes": 50,
    "foodMinutes": 0,
    "imagePath": "images/pois/gallery/tropea-santamaria-1.png",
    "imageLabel": "Santa Maria dell'Isola a Tropea",
    "description": "Uno dei punti panoramici piu celebri della costa calabrese.",
    "gallery": [
      "images/pois/gallery/tropea-santamaria-1.png",
      "images/pois/gallery/tropea-santamaria-2.png",
      "images/pois/gallery/tropea-santamaria-3.png",
      "images/pois/gallery/tropea-santamaria-4.png"
    ]
  },
  {
    "id": "tropea-marina",
    "name": "Affaccio sul mare di Tropea",
    "area": "Tropea",
    "type": "nature",
    "categoryLabel": "Costa",
    "lat": 38.67275,
    "lng": 15.89805,
    "visitMinutes": 35,
    "foodMinutes": 0,
    "imagePath": "images/pois/gallery/tropea-marina-1.png",
    "imageLabel": "mare di Tropea",
    "description": "Pausa rilassata per godersi la costa e il profilo del santuario.",
    "gallery": [
      "images/pois/gallery/tropea-marina-1.png",
      "images/pois/gallery/tropea-marina-2.png",
      "images/pois/gallery/tropea-marina-3.png"
    ]
  },
  {
    "id": "melito-centro",
    "name": "Centro di Melito di Porto Salvo",
    "area": "Melito di Porto Salvo",
    "type": "culture",
    "categoryLabel": "Centro urbano",
    "lat": 37.9204,
    "lng": 15.7779,
    "visitMinutes": 35,
    "foodMinutes": 0,
    "imagePath": "images/pois/gallery/melito-centro-1.png",
    "imageLabel": "Melito di Porto Salvo",
    "description": "Punto utile per costruire itinerari nella fascia ionica sud.",
    "gallery": [
      "images/pois/gallery/melito-centro-1.png",
      "images/pois/gallery/melito-centro-2.png",
      "images/pois/gallery/melito-centro-3.png"
    ]
  },
  {
    "id": "melito-lungomare",
    "name": "Lungomare di Melito",
    "area": "Melito di Porto Salvo",
    "type": "panorama",
    "categoryLabel": "Lungomare",
    "lat": 37.91956,
    "lng": 15.77985,
    "visitMinutes": 40,
    "foodMinutes": 0,
    "imagePath": "images/pois/gallery/melito-lungomare-1.png",
    "imageLabel": "lungomare di Melito",
    "description": "Passeggiata semplice sul mare, adatta a itinerari brevi o serali.",
    "gallery": [
      "images/pois/gallery/melito-lungomare-1.png",
      "images/pois/gallery/melito-lungomare-2.png",
      "images/pois/gallery/melito-lungomare-3.png"
    ]
  },
  {
    "id": "pentedattilo-borgo",
    "name": "Borgo di Pentedattilo",
    "area": "Pentedattilo",
    "type": "culture",
    "categoryLabel": "Borgo storico",
    "lat": 37.95439,
    "lng": 15.76102,
    "visitMinutes": 85,
    "foodMinutes": 0,
    "imagePath": "images/pois/gallery/pentedattilo-borgo-1.png",
    "imageLabel": "borgo di Pentedattilo",
    "description": "Tra i luoghi piu suggestivi dell'area grecanica, incastonato nella roccia.",
    "gallery": [
      "images/pois/gallery/pentedattilo-borgo-1.png",
      "images/pois/gallery/pentedattilo-borgo-2.png",
      "images/pois/gallery/pentedattilo-borgo-3.png",
      "images/pois/gallery/pentedattilo-borgo-4.png",
      "images/pois/gallery/pentedattilo-borgo-5.png",
      "images/pois/gallery/pentedattilo-borgo-6.png"
    ]
  },
  {
    "id": "condofuri-marina",
    "name": "Condofuri Marina",
    "area": "Condofuri",
    "type": "nature",
    "categoryLabel": "Costa",
    "lat": 37.93324,
    "lng": 15.87166,
    "visitMinutes": 45,
    "foodMinutes": 0,
    "imagePath": "images/pois/gallery/condofuri-marina-1.png",
    "imageLabel": "Condofuri Marina",
    "description": "Tratto di costa tranquillo, ideale per una sosta mare e relax.",
    "gallery": [
      "images/pois/gallery/condofuri-marina-1.png",
      "images/pois/gallery/condofuri-marina-2.png",
      "images/pois/gallery/condofuri-marina-3.png",
      "images/pois/gallery/condofuri-marina-4.png"
    ]
  },
  {
    "id": "ammendolea-borgo",
    "name": "Borgo di Amendolea",
    "area": "Amendolea",
    "type": "culture",
    "categoryLabel": "Borgo storico",
    "lat": 37.98873,
    "lng": 15.89287,
    "visitMinutes": 75,
    "foodMinutes": 0,
    "imagePath": "images/pois/gallery/ammendolea-borgo-1.png",
    "imageLabel": "borgo di Amendolea",
    "description": "Piccolo borgo dell'area grecanica con forte carattere paesaggistico.",
    "gallery": [
      "images/pois/gallery/ammendolea-borgo-1.png",
      "images/pois/gallery/ammendolea-borgo-2.png",
      "images/pois/gallery/ammendolea-borgo-3.png",
      "images/pois/gallery/ammendolea-borgo-4.png",
      "images/pois/gallery/ammendolea-borgo-5.png"
    ]
  },
  {
    "id": "bova-borgo",
    "name": "Borgo di Bova",
    "area": "Bova",
    "type": "culture",
    "categoryLabel": "Borgo ellenofono",
    "lat": 37.9969,
    "lng": 15.9329,
    "visitMinutes": 85,
    "foodMinutes": 0,
    "imagePath": "images/pois/gallery/bova-borgo-1.png",
    "imageLabel": "borgo di Bova",
    "description": "Uno dei paesi piu identitari dell'area grecanica, tra storia e tradizioni.",
    "gallery": [
      "images/pois/gallery/bova-borgo-1.png",
      "images/pois/gallery/bova-borgo-2.png",
      "images/pois/gallery/bova-borgo-3.png",
      "images/pois/gallery/bova-borgo-4.png",
      "images/pois/gallery/bova-borgo-5.png"
    ]
  },
  {
    "id": "bova-belvedere",
    "name": "Belvedere di Bova",
    "area": "Bova",
    "type": "panorama",
    "categoryLabel": "Belvedere",
    "lat": 37.9961,
    "lng": 15.9342,
    "visitMinutes": 30,
    "foodMinutes": 0,
    "imagePath": "images/pois/bova-belvedere.jpg",
    "imageLabel": "belvedere di Bova",
    "description": "Affaccio sull'Aspromonte e sulla costa ionica, ottimo per una tappa fotografica."
  },
  {
    "id": "gerace-centro",
    "name": "Centro storico di Gerace",
    "area": "Gerace",
    "type": "culture",
    "categoryLabel": "Borgo medievale",
    "lat": 38.27106,
    "lng": 16.22093,
    "visitMinutes": 95,
    "foodMinutes": 0,
    "imagePath": "images/pois/gallery/gerace-centro-1.png",
    "imageLabel": "centro storico di Gerace",
    "description": "Borgo medievale dell'entroterra con un tessuto urbano tra i piu belli della zona.",
    "gallery": [
      "images/pois/gallery/gerace-centro-1.png",
      "images/pois/gallery/gerace-centro-2.png",
      "images/pois/gallery/gerace-centro-3.png",
      "images/pois/gallery/gerace-centro-4.png",
      "images/pois/gallery/gerace-centro-5.png"
    ]
  },
  {
    "id": "gerace-cattedrale",
    "name": "Cattedrale di Gerace",
    "area": "Gerace",
    "type": "culture",
    "categoryLabel": "Architettura religiosa",
    "lat": 38.27065,
    "lng": 16.22156,
    "visitMinutes": 45,
    "foodMinutes": 0,
    "imagePath": "images/pois/gallery/gerace-cattedrale-1.png",
    "imageLabel": "cattedrale di Gerace",
    "description": "Una delle visite piu forti per chi ama chiese storiche e architettura.",
    "gallery": [
      "images/pois/gallery/gerace-cattedrale-1.png",
      "images/pois/gallery/gerace-cattedrale-2.png",
      "images/pois/gallery/gerace-cattedrale-3.png",
      "images/pois/gallery/gerace-cattedrale-4.png",
      "images/pois/gallery/gerace-cattedrale-5.png"
    ]
  },
  {
    "id": "locri-parco",
    "name": "Parco Archeologico di Locri Epizefiri",
    "area": "Locri",
    "type": "culture",
    "categoryLabel": "Archeologia",
    "lat": 38.24158,
    "lng": 16.26653,
    "visitMinutes": 95,
    "foodMinutes": 0,
    "imagePath": "images/pois/gallery/locri-parco-1.png",
    "imageLabel": "parco archeologico di Locri Epizefiri",
    "description": "Sito archeologico chiave per un itinerario storico nel versante ionico.",
    "gallery": [
      "images/pois/gallery/locri-parco-1.png",
      "images/pois/gallery/locri-parco-2.png",
      "images/pois/gallery/locri-parco-3.png",
      "images/pois/gallery/locri-parco-4.png",
      "images/pois/gallery/locri-parco-5.png",
      "images/pois/gallery/locri-parco-6.png"
    ]
  },
  {
    "id": "locri-lungomare",
    "name": "Lungomare di Locri",
    "area": "Locri",
    "type": "panorama",
    "categoryLabel": "Lungomare",
    "lat": 38.2387,
    "lng": 16.2596,
    "visitMinutes": 35,
    "foodMinutes": 0,
    "imagePath": "images/pois/gallery/locri-lungomare-1.png",
    "imageLabel": "lungomare di Locri",
    "description": "Una sosta mare semplice da inserire in una giornata sul versante ionico.",
    "gallery": [
      "images/pois/gallery/locri-lungomare-1.png",
      "images/pois/gallery/locri-lungomare-2.png",
      "images/pois/gallery/locri-lungomare-3.png",
      "images/pois/gallery/locri-lungomare-4.png"
    ]
  },
  {
    "id": "tropea-pranzo",
    "name": "Pranzo tipico a Tropea",
    "area": "Tropea",
    "type": "food",
    "categoryLabel": "Ristorazione",
    "lat": 38.67516,
    "lng": 15.89618,
    "visitMinutes": 75,
    "foodMinutes": 75,
    "imagePath": "images/pois/tropea-pranzo.jpg",
    "imageLabel": "piatto tipico a Tropea",
    "description": "Pausa gastronomica da inserire tra centro storico e affacci sul mare."
  },
  {
    "id": "scilla-cena",
    "name": "Cena di pesce a Scilla",
    "area": "Scilla",
    "type": "food",
    "categoryLabel": "Esperienza gastronomica",
    "lat": 38.25253,
    "lng": 15.7162,
    "visitMinutes": 80,
    "foodMinutes": 80,
    "imagePath": "images/pois/scilla-cena.jpg",
    "imageLabel": "cena di pesce a Scilla",
    "description": "Sosta food perfetta da abbinare a Chianalea e al tramonto."
  },
  {
    "id": "bova-degustazione",
    "name": "Degustazione nell'area grecanica",
    "area": "Bova",
    "type": "food",
    "categoryLabel": "Sapori locali",
    "lat": 37.99658,
    "lng": 15.93312,
    "visitMinutes": 60,
    "foodMinutes": 60,
    "imagePath": "images/pois/bova-degustazione.jpg",
    "imageLabel": "degustazione nell'area grecanica",
    "description": "Pausa gastronomica per percorsi tra borghi e tradizioni dell'entroterra."
  }
];
